test:
  key1:
    value1: "abc-qa"
    value2: "def-qa"
  key2:
    value1: 2
    value2: 2.4

db:
  uri: someqauri
  username: someqausername
  password: someqapassword # This will be in some vault.
